config/routes.rb
Rails.application.routes.draw do
  # get "/tasks", to: "tasks#index"
  # get "/tasks/new", to: "tasks#new", as: :new_task
  # post "/tasks", to: "tasks#create"
  # get "/tasks/:id", to: "tasks#show", as: :task # show has to be after create
  resources :tasks
end

# make new html pages for index not for /tasks because they need to match up
# with methods in the controller

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all # Remember, class methods have to be SINGULAR!
  end

  def show
    @task = Task.find(params[:id])
  end

  def create
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_for(task) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :details %>
  <%= f.text_field :details %>
  <%= f.label :completed %>
  <%= f.boolean false %>
  <%= f.submit "create" %>
<% end %>

app/views/tasks/index.html.erb
<h1>My Tasks</h1>
<div class="task-card">
  <ul>
    <% @tasks.each do |task| %>
      <label class="container">
        <li><%= link_to task.title, task_path(task) %>
          <input type="checkbox">
          <span class="checkmark"></span>
        </li>
      </label>
    <% end %>
  </ul>
</div>
<div>
  <%= link_to "New task", new_task_path %>
</div>

app/views/tasks/new.html.erb
<h1>Create a new task!</h1>
<%= render "form", task: @task %>

<%= link_to "Back to tasks", tasks_path %>

app/views/tasks/show.html.erb
<h2><%= @task.title %></h2>
<p><%= @task.details %></p>
<p><%= @task.completed %></p>

<%= link_to "Back to tasks", tasks_path %>